# Generated by Django 5.1.2 on 2024-11-08 15:44
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_alter_new_pub_date_alter_post_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="new",
            name="pub_date",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="news.author"),
        ),
    ]
