# Generated by Django 5.1.3 on 2024-11-20 09:18
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0006_category_subscribers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="postCategory",
            new_name="category",
        ),
    ]
