# Generated by Django 5.1.3 on 2025-01-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0007_rename_postcategory_post_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name_en_us",
            field=models.CharField(
                help_text="category name", max_length=32, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="name_ru",
            field=models.CharField(
                help_text="category name", max_length=32, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="text_en_us",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="text_ru",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="title_en_us",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="title_ru",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="category name", max_length=32, unique=True
            ),
        ),
    ]
