# Generated by Django 5.1.3 on 2025-01-28 16:20
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0008_category_name_en_us_category_name_ru_post_text_en_us_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "permissions": [
                    ("can_add_comment", "Can add comment"),
                    ("can_delete_comment", "Can delete comment"),
                ]
            },
        ),
    ]
