# Generated by Django 5.1.3 on 2025-01-28 16:30
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0009_alter_comment_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"permissions": [("can_add_comment", "Can add comment")]},
        ),
    ]
