# Generated by Django 5.1.3 on 2025-05-13 15:17
import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0010_alter_post_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="text_en_us",
        ),
        migrations.RemoveField(
            model_name="post",
            name="text_ru",
        ),
        migrations.AlterField(
            model_name="post",
            name="text",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text"),
        ),
    ]
