name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DJANGO_SETTINGS_MODULE: NewsPortal.settings
      SECRET_KEY: dummy
      DEBUG: '0'

    steps:
      - uses: actions/checkout@v3


